#!/bin/sh

mkdir -p /root/.ssh
cat << EOI > /etc/dropbear/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEAq3Rd+hi08wKBKb6BGH11Da7ZPLYfiwv5CsG1BYlOLlmBJnoSZ/kIelIFS9aKnupPmIW4OwK6ApvfZlU411z6XQyORDwRUwbbVCv1ckdgpeDc0HT3b6lURIdal4vq3I/JkhHxJ8iehdSCDUdcYaDjCC3BS/tldHMuqf4Dgr5bLwkQSjqzC9yCXSKoIjKXcsaix3NakHYu4Skm5HvjYMrtrUkWX92tX0ekX8fJ7K7C2021jJ9xlgoXMwTQN8WVxWAAu3qvcyk6uadjK6x7KTryUvwnQRGLAEgLZNkMxHQclMYlz9NtQ6ESClKWVtL0vqwUOQE6kDwVzjXD5BDxMpn/ZvPFle6Oz4GwSypFv/9XNdYWby0rowDMTZ6UY4bjT1pzJVIWj8TBNzd2SFJH6dwEGs7RWe29tXhl2CpKNcVZ4T6lg83OH9HM/rWdqpSrKOKoS2yux8XxxuDHApRic32T0bNie2qKxKK7jXex1Ev5Q4wPiz/GunnPpgiLnYeLKBFezSLcma6wmus0N93cqQaFOBL3UjVptAdVYMDqIincpqBQTBoUuSntM5JdWFSbboIUMfER12LZn3dX73SucHFKdnOZPOCJ1gviYjlSfwstV9vTJnOJqU2nfzAY0sPgBcPgJLLBF3JQFFfTYz4GkiRM/lRq/S298dJ5dRR4Ej9qkPM= root@Sys-RDNS-NS1
ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAiKt3wMRpC5ZF31E7uKk4yHotymmdA3QNYTOYKRy2ZSCBBZJGZ10EzQcHZgH30skVKMiRF/7dpcdM4FqYfQ1az1eHxKpTWWbMdnhs/JHXwEMoSIxceeOQKirWhbwshCkbOFZ76PBVIV34cQeUMxxVd/cy5w+noJ502gbpD9A0i+9RdWu8luQbXUKOi1oM2wilfd1HLc0GqsXd6lEdAgBR5u0C45NVjPf5rj7Rb+6aXe0iHfqJnln0qE2xNXrCTMkuLC6q1Qyh5SBMBCPc0TKgAml/gdd2p+JpbJatcCR3bkgppg8rBFXm7YRvFNvrEWCdhDNYDLFGvbSvQJKmqGZSYw== PhuongNH
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClkSycJha1VyTFbqKVrB+3oMlAGJmb/kGn49KggsBIFdlLLRcHF9wH/tF5VFWhz9QVWqy9gAwxDLgdSRmUBNirW1DoB/kbCKLnFEEKppM7Me6fOMqiPkiQGp9DY5jJ4CpB3ZzWOxUDhBXIpoXmE/ayrUkNYB0GBGF/TfRHZwTzodsofK3T7yIHi8p5TdqpODeAiedUUNV9MX+kM0jS0o8gpp7Onxb3xpuuS+nbcmcIfkdFNhnVWv4IZufxDx1/6DUO3cd+h92e04/DvBiGKH6RG5ilcdl55titV+yHYKsTr4dla/Zz+6VOry7uXgJtoT11MPxRrDm5hj6GEoCmbn4/ root@db4-123d28
EOI
uci set dropbear.@dropbear[0].PasswordAuth='on'
uci set dropbear.@dropbear[0].RootPasswordAuth='on'
chmod -R u=rwX,go= /etc/dropbear
uci commit dropbear
/etc/init.d/dropbear restart

cat << EOI > /etc/init.d/autoipset
#!/bin/sh /etc/rc.common

# - # chmod 755 /etc/init.d/autoipset
# - # /etc/init.d/autoipset enable
# - # /etc/init.d/autoipset start

# queue this init script to start (i.e., create IPSet) right before dnsmasq starts (19)
START=18

setipset() {
dns3=$(sms_tool -d /dev/ttyUSB2 at "at+cgcontRDP" | awk '{print $2}' | cut -d , -f 7 | sed 's/ //g' | sed -e 's/[\t ]//g;/^$/d' || sms_tool -d /dev/ttyUSB5 at "at+cgcontRDP" | awk '{print $2}' | cut -d , -f 7 | sed 's/ //g' | sed -e 's/[\t ]//g;/^$/d')
        ipset -N youtube hash:ip
    ipset -N tiktok hash:ip
ipset -N zalo hash:ip
ipset -N vnpt-dns hash:ip
ipset -N tiktok hash:ip
ipset add vnpt-dns 203.162.4.191
ipset add vnpt-dns 203.162.0.181
ipset add vnpt-dns 203.162.4.190
ipset add vnpt-dns 203.162.0.180
ipset add vnpt-dns $dns3
ipset add zalo 118.102.0.0/21
ipset add zalo 118.102.0.0/21
ipset add zalo 120.138.64.0/20
ipset add zalo 122.201.12.0/22
ipset add zalo 122.201.8.0/21
ipset add zalo 45.127.252.0/22
ipset add zalo 49.213.100.0/22
ipset add zalo 49.213.104.0/22
ipset add zalo 49.213.108.0/22
ipset add zalo 49.213.116.0/22
ipset add zalo 49.213.120.0/22
ipset add zalo 49.213.124.0/22
ipset add zalo 49.213.64.0/20
ipset add zalo 49.213.80.0/21
ipset add zalo 49.213.88.0/23
ipset add zalo 49.213.90.0/23
ipset add zalo 49.213.92.0/23
ipset add zalo 49.213.94.0/23
ipset add zalo 49.213.96.0/19
ipset add zalo 61.28.224.0/19
}

start() {
        setipset
}
EOI
chmod 755 /etc/init.d/autoipset
/etc/init.d/autoipset enable
/etc/init.d/autoipset start

sed -i -re 's/^(option check_signature.*)/#\1/g' /etc/opkg.conf

uci set network.lan.ipaddr="192.168.14.1"
uci commit network
/etc/init.d/network restart


uci set 'network.lan.ipv6=0'
uci set 'network.wan.ipv6=0'
uci set 'dhcp.lan.dhcpv6=disabled'
/etc/init.d/odhcpd disable
/etc/init.d/odhcpd stop
uci commit

uci -q delete dhcp.lan.dhcpv6
uci -q delete dhcp.lan.ra
uci commit dhcp
/etc/init.d/odhcpd restart

uci set network.lan.delegate="0"
uci commit network
/etc/init.d/network restart


wifi_password="06061988P"

for radio in 'wifinet0' 'wifinet1'
do
    # Set country
    uci set wireless."$radio".country="CN"

    # Enable radio
    uci set wireless."$radio".disabled="0"

    # Set SSID and password
    uci set wireless."$radio".ssid="MyHome2"
    uci set wireless."$radio".encryption="psk-mixed"
    uci set wireless."$radio".key="$wifi_password"

    uci -q commit wireless
done
uci set wireless.radio0.txpower="30"
uci set wireless.radio1.txpower="30"
uci -q commit wireless
wifi reload

uci delete system.ntp.server
uci add_list system.ntp.server='0.vn.pool.ntp.org'
uci add_list system.ntp.server='2.asia.pool.ntp.org'
uci add_list system.ntp.server='1.asia.pool.ntp.org'
uci add_list system.ntp.server='125.235.4.198'
uci add_list system.ntp.server='115.73.220.183'
uci add_list system.ntp.server='222.255.146.26'


